[project]
name = "final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "mysqlclient>=2.2.8",
    "pandas>=3.0.2",
    "pathlib>=1.0.1",
    "requests>=2.33.1",
    "sqladmin[full]>=0.25.0",
    "sqlalchemy>=2.0.49",
]
