"""add threshold fields to dim_parameters

Revision ID: 639662397362
Revises: 
Create Date: 2026-04-30 17:27:59.030029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639662397362'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_parameters', sa.Column('physical_min', sa.Float(), nullable=True))
    op.add_column('dim_parameters', sa.Column('physical_max', sa.Float(), nullable=True))
    op.add_column('dim_parameters', sa.Column('gdk_daily', sa.Float(), nullable=True))
    op.add_column('dim_parameters', sa.Column('gdk_short_term', sa.Float(), nullable=True))
    op.add_column('dim_parameters', sa.Column('gdk_unit_basis', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_parameters', 'gdk_unit_basis')
    op.drop_column('dim_parameters', 'gdk_short_term')
    op.drop_column('dim_parameters', 'gdk_daily')
    op.drop_column('dim_parameters', 'physical_max')
    op.drop_column('dim_parameters', 'physical_min')
    # ### end Alembic commands ###
